spring:
  application:
    name: lessons
  datasource:
    url: "jdbc:postgresql://localhost:5432/security-lessons"
    password: test
    username: admin
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

jpa:
  hibernate:
    ddl-auto: none

server:
  port: 8081
  error:
    include-errors: always

app:
  jwt:
    issuer: lessons
    access-ttl: 86400000
    secret-base64: ${JWT_SECRET_KEY}