spring.application.name=exercise-3
spring.datasource.url=jdbc:postgresql://localhost:5432/jpa-exercise-3
spring.datasource.password=test
spring.datasource.username=admin
jpa.hibernate.ddl-auto=create

server.port=8081
server.error.include-errors=always