services:
  db:
    container_name: exercise-1
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=exercise-1
    ports:
      - "5432:5432"
